name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Syntax check
      run: |
        find . -name "*.py" | xargs pylint
        find . -name "*.py" | xargs black --check

    - name: Run linters
      run: |
        pylint projectx.py
        flake8 projextx.py
